# This is a basic workflow to help you get started with Actions

name: Test Installed Tools

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  locate:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: which vswhere.exe
        continue-on-error: true
        run: |
          which vswhere.exe
          
      - name: which sqlpackage
        continue-on-error: true
        run: |
          C:/ProgramData/Chocolatey/bin/vswhere.exe -find "**\\SQLDB\\**\\SqlPackage.exe"

      - name: which sqlpackage
        continue-on-error: true
        run: |
          which sqlpackage

      - name: find sqlpackage
        continue-on-error: true
        run: |
          find / -type f -name "sqlpackage.exe"

      - name: find vswhere.exe
        continue-on-error: true
        run: |
          find / -type f -name "vswhere.exe"
  
  
    