# This is a basic workflow to help you get started with Actions

name: Test Installed Tools

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  listPrograms:
    name: Dir of C:/Program Files
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      - name: dir C:\Program Files
        continue-on-error: true
        shell: pwsh
        run: |
            Write-Host "Listing contents of $(Get-Location)"
            Get-ChildItem -Attributes !ReparsePoint | ForEach-Object {
              Write-Host $_.FullName
            }
        working-directory: C:\Program Files\

  locate:
    name: Find SqlPackage.exe
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: which vswhere.exe
        continue-on-error: true
        run: |
          which vswhere.exe
          
      - name: vswhere sqlpackage
        continue-on-error: true
        run: |
          vswhere.exe -find "**\\SQLDB\\**\\SqlPackage.exe"
        #   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\SqlPackage.exe
  
    