# This is a basic workflow to help you get started with Actions

name: Test Variables

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set Vars
        shell: pwsh
        run: |
          $someVar = "oap=9876;sdf f=543;"
          echo "some_var=$someVar" | Out-File -Append -FilePath $env:GITHUB_ENV

          $someOtherVar = "abc=12345;de f=67890;"
          echo "some_other_var=$someOtherVar" | Out-File -Append -FilePath $env:GITHUB_ENV

      - name: List vars Pwsh
        shell: pwsh
        run: |
          dir env:


      - name: List vars sh
        run: |
          env

    
      - name: Check vars Pwsh
        shell: pwsh
        run: |

          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Write-Host "$"+"env"+":"+"some_var = $env:some_var";
          Write-Host "$"+"env"+":"+"some_other_var = $env:some_other_var";
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Write-Host "$"+"Env"+":"+"some_var = $Env:some_var";
          Write-Host "$"+"Env"+":"+"some_other_var = $Env:some_other_var";
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Write-Host "$"+"ENV"+":"+"some_var = $ENV:some_var";
          Write-Host "$"+"ENV"+":"+"some_other_var = $ENV:some_other_var";
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Write-Host ""+"env"+":"+"some_var = env:some_var";
          Write-Host ""+"env"+":"+"some_other_var = env:some_other_var";
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Write-Host "$"+""+""+"some_var = $some_var";
          Write-Host "$"+""+""+"some_other_var = $some_other_var";
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";

        env:
          sv: ${{ env.some_var }}
          sov: ${{ env.some_other_var }}

      - name: Check vars SH
        run: |

          echo "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   "
          echo $some_var
          echo $some_other_var
          echo "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   "

        env:
          sv: ${{ env.some_var }}
          sov: ${{ env.some_other_var }}
  