# This is a basic workflow to help you get started with Actions

name: Test Variables

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:

      - name: Set Vars
        id: setvar01
        shell: pwsh
        run: |
          $someVar = "oap=9876;sdf f=543;"
          echo "some_var=$someVar" | Out-File -Append -FilePath $env:GITHUB_ENV

          $someOtherVar = "abc=12345;de f=67890;"
          echo "some_other_var=$someOtherVar" | Out-File -Append -FilePath $env:GITHUB_ENV

          $someThirdVar = "frt=9374;oe s=92837;"
          echo "::set-output name=some_third_var::$someOtherVar"

      - name: List vars Pwsh
        shell: pwsh
        run: |
          dir env:


      - name: List vars sh
        run: |
          env

    
      - name: Check vars Pwsh
        shell: pwsh
        run: |

          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Write-Host "$"+"env"+":"+"some_var = $env:some_var";
          Write-Host "$"+"env"+":"+"some_other_var = $env:some_other_var";
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Write-Host "$"+"Env"+":"+"some_var = $Env:some_var";
          Write-Host "$"+"Env"+":"+"some_other_var = $Env:some_other_var";
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Write-Host "$"+"ENV"+":"+"some_var = $ENV:some_var";
          Write-Host "$"+"ENV"+":"+"some_other_var = $ENV:some_other_var";
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Write-Host ""+"env"+":"+"some_var = env:some_var";
          Write-Host ""+"env"+":"+"some_other_var = env:some_other_var";
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";
          Write-Host "$"+""+""+"some_var = $some_var";
          Write-Host "$"+""+""+"some_other_var = $some_other_var";
          Write-Host "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ";

        env:
          sv: ${{ env.some_var }}
          sov: ${{ env.some_other_var }}

      - name: Check vars SH
        run: |

          echo "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   "
          echo $some_var
          echo $some_other_var
          echo "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   "

        env:
          sv: ${{ env.some_var }}
          sov: ${{ env.some_other_var }}
  
      - name: what is GITHUB_OUTPUT
        run: |

          echo "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   "
          echo $GITHUB_OUTPUT
          echo "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   "

    outputs:
      some_var: ${{ steps.setvar01.outputs.some_var }}
      some_other_var: ${{ steps.setvar01.outputs.some_other_var }}
      some_third_var: ${{ steps.setvar01.outputs.some_third_var }}

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    env:
      some_var: ${{needs.job1.outputs.some_var}}
      some_third_var: ${{needs.job1.outputs.some_third_var}}

    steps:
      - name: Check vars SH
        env:
          some_other_var: ${{needs.job1.outputs.some_other_var}}
        run: |

          echo "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   "
          echo $some_var
          echo $some_other_var
          echo $some_third_var
          echo "✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   ✨   "
